// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRBoTBZUDkUqp6gBhs9Pj0P8xexuYFjFU',
    appId: '1:680754775838:web:bd5c8094f38667af852b0f',
    messagingSenderId: '680754775838',
    projectId: 'ai-business-card-e1cde',
    authDomain: 'ai-business-card-e1cde.firebaseapp.com',
    storageBucket: 'ai-business-card-e1cde.firebasestorage.app',
    measurementId: 'G-WJP9JGYE1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvzerbKgUH9s64gxbmnRrDo1wlb5e4KKA',
    appId: '1:680754775838:android:dd62dbf0540c802d852b0f',
    messagingSenderId: '680754775838',
    projectId: 'ai-business-card-e1cde',
    storageBucket: 'ai-business-card-e1cde.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAocUD-2ECMyYtFXHmpv4nZoAjZopoMaRc',
    appId: '1:680754775838:ios:35898e0f215f95e8852b0f',
    messagingSenderId: '680754775838',
    projectId: 'ai-business-card-e1cde',
    storageBucket: 'ai-business-card-e1cde.firebasestorage.app',
    iosBundleId: 'com.business.card.scanner.reader.maker',
  );
}
